# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bruh < Formula
  desc "Command-line tool for scanning and updating the API version of Azure resources in Bicep files"
  homepage "https://github.com/christosgalano/bruh"
  version "1.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_darwin_arm64.tar.gz"
      sha256 "979b15bb9a6fd008e05aa210a5ce72e549e739212c579cdbb4281f87c905ab03"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_darwin_amd64.tar.gz"
      sha256 "36cc7aca2412ae9e257ceb5c9739c96eaaf8a4a1a59334112715af4301848277"

      def install
        bin.install "bruh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_arm64.tar.gz"
      sha256 "cc58ba1de2a5310d62754fbefb499df0ac359a718cfc1968a4341cf531dd4429"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_amd64.tar.gz"
      sha256 "31735f9f77b756386b92f180942d52f0fbd8c2394a85a51a767d7b4e35b1a29c"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_arm.tar.gz"
      sha256 "12d999ce9814699503e476db8ac3ed54432d26877af5af5fc23ac623d6cef438"

      def install
        bin.install "bruh"
      end
    end
  end

  test do
    system "#{bin}/bruh", "--help"
  end
end
