# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bruh < Formula
  desc "Command-line tool for scanning and updating the API version of Azure resources in Bicep files"
  homepage "https://github.com/christosgalano/bruh"
  version "1.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_darwin_arm64.tar.gz"
      sha256 "95f139b4b2f8394b25c54fe13ea40bbfd5d953825e236828e1b3a5cf419c8c72"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_darwin_amd64.tar.gz"
      sha256 "35b062dc054d1d1df437d7947a56107725777dd2a21ace47611f1ef5bae02ed2"

      def install
        bin.install "bruh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_amd64.tar.gz"
      sha256 "b251bca6739023544fa72f02d1d08138b7297fe2b996d83b9cf95f2c9540af9a"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_arm64.tar.gz"
      sha256 "460d7fe913ad8c0ab241032e575859743a3beb60fb26168baf4ee20add8663ca"

      def install
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/christosgalano/bruh/releases/download/v1.0.0/bruh_linux_arm.tar.gz"
      sha256 "6b5f1513f71153b05e49e62751b8fd12a46d25746f8cec46d9ff6c16a125f6a7"

      def install
        bin.install "bruh"
      end
    end
  end

  test do
    system "#{bin}/bruh", "--help"
  end
end
